### ISSUE TITLE
Can't run playbook twice

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/infinispan#20]
##### SUMMARY

A very simple playbook, deploying the service and configure a replicated cache, fails to run twice.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```

```

##### STEPS TO REPRODUCE

```
# ansible-galaxy collection install middleware_automation.infinispan
#  ansible-galaxy collection install community.general
#  ansible-playbook -i inventory playbook.yml 
(pass successfully)
#  ansible-playbook -i inventory playbook.yml 
...
TASK [middleware_automation.infinispan.infinispan_cache : Check cache myCache state] ***************************************************
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "connection": "close", "content_length": "1283", "content_type": "application/json", "cookies": {}, "cookies_string": "", "elapsed": 0, "json": {"bounded": false, "configuration": {"replicated-cache": {"encoding": {"key": {"media-type": "application/x-protostream"}, "value": {"media-type": "application/x-protostream"}}, "expiration": {"interval": 60000, "lifespan": -1, "max-idle": -1}, "locking": {"acquire-timeout": 10000, "concurrency-level": 32, "isolation": "REPEATABLE_READ", "striping": false}, "memory": {"storage": "HEAP", "when-full": "NONE"}, "mode": "SYNC", "partition-handling": {"merge-policy": "NONE", "when-split": "ALLOW_READ_WRITES"}, "statistics": false, "transaction": {"locking": "OPTIMISTIC", "mode": "NONE"}, "unreliable-return-values": false}}, "has_remote_backup": false, "indexed": false, "indexing_in_progress": false, "persistent": false, "queryable": true, "rehash_in_progress": false, "secured": false, "size": 0, "statistics": false, "stats": {"average_read_time": -1, "average_read_time_nanos": -1, "average_remove_time": -1, "average_remove_time_nanos": -1, "average_write_time": -1, "average_write_time_nanos": -1, "current_number_of_entries": -1, "current_number_of_entries_in_memory": -1, "data_memory_used": -1, "evictions": -1, "hits": -1, "misses": -1, "off_heap_memory_used": -1, "remove_hits": -1, "remove_misses": -1, "required_minimum_number_of_nodes": -1, "retrievals": -1, "stores": -1, "time_since_reset": -1, "time_since_start": -1, "total_number_of_entries": -1}, "transactional": false}, "msg": "Status code was 200 and not [404]: OK (1283 bytes)", "redirected": false, "status": 200, "url": "http://localhost:11222/rest/v2/caches/myCache"}

```

```yaml
---
- name: Playbook for infinispan Hosts
  hosts: infinispan
  become: yes
  collections:
    - middleware_automation.infinispan
  vars:
    jdg_supervisor_password: "thisshouldbeaverysecurepassword"
  roles:
    - role: infinispan
      infinispan_supervisor_password: "{{ jdg_supervisor_password }}"
      infinispan_users: []

    - role: infinispan_cache
      infinispan_deployer_user: "supervisor"
      infinispan_deployer_password: "{{ jdg_supervisor_password }}"
      infinispan_cache_config:
        name: myCache
        template: 'replicated'

```

##### EXPECTED RESULTS

The playbook can be run multiple time.
